version: "2.1"
services:
  app:
      build: .
      command: /bin/bash -c "sleep 20; ./init.sh"
      ports:
        - "8000:8000"
      links:
        - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: petros
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: 'loan'
    ports:
      - "5432:5432"