version: "2"
services:
  app:
      build: .
      command: python manage.py runserver
      ports:
        - "8000:8000"
      links:
        - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: petros
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: 'loan'
    ports:
      - "5432:5432"